import { Identity } from 'src/app/common/entities/identity';

export class IdentityData {

  public static identities: Identity[] = [
    {
      empId: '1',
      name: 'Eric Tan',
      email: 'eric.tan@auckland.ac.nz',
      firstName: 'Eric',
      lastName: 'Tan',
      staffUpi: 'etan221',
      faculty: 'Auckland Bioengineering Institute',
      nameDisplay: 'Eric Tan',
    }, 
    {
      empId: '2',
      name: 'Avishek Kumar',
      email: 'avishek.kumar@auckland.ac.nz',
      firstName: 'Avishek',
      lastName: 'Kumar',
      staffUpi: 'akum036',
      faculty: 'Engineering',
      nameDisplay: 'Avishek Kumar',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
    {
      empId: '3',
      name: 'Shahnoor Islam',
      email: 'c@c.com',
      firstName: 'Shahnoor',
      lastName: 'Islam',
      staffUpi: 'misl938',
      faculty: 'Education and Social Work',
      nameDisplay: 'Shahnoor Islam',
    }, 
  ];
}