import { PsStaff } from '../entities/psStaff';

export class StaffData {
  // public static identities: Identity[] = [
  //   {
  //     empId: '1',
  //     name: 'Eric Tan',
  //     email: 'eric.tan@auckland.ac.nz',
  //     firstName: 'Eric',
  //     lastName: 'Tan',
  //     staffUpi: 'etan221',
  //     faculty: 'Auckland Bioengineering Institute',
  //     nameDisplay: 'Eric Tan',
  //   },
  //   {
  //     empId: '2',
  //     name: 'Avishek Kumar',
  //     email: 'avishek.kumar@auckland.ac.nz',
  //     firstName: 'Avishek',
  //     lastName: 'Kumar',
  //     staffUpi: 'akum036',
  //     faculty: 'Engineering',
  //     nameDisplay: 'Avishek Kumar',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  //   {
  //     empId: '3',
  //     name: 'Shahnoor Islam',
  //     email: 'c@c.com',
  //     firstName: 'Shahnoor',
  //     lastName: 'Islam',
  //     staffUpi: 'misl938',
  //     faculty: 'Education and Social Work',
  //     nameDisplay: 'Shahnoor Islam',
  //   },
  // ];

  // public static staff: PsStaff[] = [
  //   {
  //     BUSINESS_UNIT_DESC: 'Engineering',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Alec',
  //     GRADE: 'GU',
  //     LAST_NAME: 'Asadov',
  //     LAYOFF_EXEMPT_RSN: 'PS2022SEC',
  //     NATIONAL_ID: 'AASA001',
  //     POSITION_DESCR: 'Senior Technologist',
  //     STEP: 3,
  //     STEP_ENTRY_DT: '1/02/2020',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Business and Economics',
  //     COMP_RATE_DESCR: 'Director Allce',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Andrew',
  //     GRADE: 'PTS',
  //     LAST_NAME: 'Eberhard',
  //     LAYOFF_EXEMPT_RSN: 'AS2022SEC',
  //     NATIONAL_ID: 'AEBE001',
  //     POSITION_DESCR: 'Director - GSM',
  //     STEP: 4,
  //     STEP_ENTRY_DT: '18/01/2022',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 1000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Business and Economics',
  //     COMP_RATE_DESCR: 'Retention Allowance',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Andrew',
  //     GRADE: 'PTS',
  //     LAST_NAME: 'Eberhard',
  //     LAYOFF_EXEMPT_RSN: 'AS2022SEC',
  //     NATIONAL_ID: 'AEBE001',
  //     POSITION_DESCR: 'Director - GSM',
  //     STEP: 4,
  //     STEP_ENTRY_DT: '18/01/2022',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 1000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Business and Economics',
  //     COMP_RATE_DESCR: 'Associate Dean Allce',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Andrew',
  //     GRADE: 'PTS',
  //     LAST_NAME: 'Eberhard',
  //     LAYOFF_EXEMPT_RSN: 'AS2022SEC',
  //     NATIONAL_ID: 'AEBE001',
  //     POSITION_DESCR: 'Director - GSM',
  //     STEP: 4,
  //     STEP_ENTRY_DT: '18/01/2022',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 1000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Business and Economics',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Andrew',
  //     GRADE: 'PTS',
  //     LAST_NAME: 'Eberhard',
  //     LAYOFF_EXEMPT_RSN: 'AS2022SEC',
  //     NATIONAL_ID: 'AEBE001',
  //     POSITION_DESCR: 'Director - GSM',
  //     STEP: 4,
  //     STEP_ENTRY_DT: '18/01/2022',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Libraries & Learning Services',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Anupom',
  //     GRADE: 'BU',
  //     LAST_NAME: 'Kabir',
  //     LAYOFF_EXEMPT_RSN: 'PS2022SEC',
  //     NATIONAL_ID: 'AKAB010',
  //     POSITION_DESCR: 'Materials Assistant',
  //     STEP: 1,
  //     STEP_ENTRY_DT: '17/09/2021',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Medical and Health Sciences',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Adrina Hema',
  //     GRADE: 'FU',
  //     LAST_NAME: 'Khemlani',
  //     LAYOFF_EXEMPT_RSN: 'PS2022SEC',
  //     NATIONAL_ID: 'AKHE005',
  //     POSITION_DESCR: 'Senior Research Technician',
  //     STEP: 0,
  //     STEP_ENTRY_DT: '1/04/2021',
  //     TERMINATION_DT: '30/11/2023',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Fixed Term',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Business and Economics',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Bram',
  //     GRADE: 'LRS',
  //     LAST_NAME: 'Van Wiele',
  //     LAYOFF_EXEMPT_RSN: 'AS2022SEC',
  //     NATIONAL_ID: 'BVAN212',
  //     POSITION_DESCR: 'Lecturer',
  //     STEP: 7,
  //     STEP_ENTRY_DT: '2/03/2022',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Business and Economics',
  //     COMP_RATE_DESCR: 'Recruitment Allowance',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Bram',
  //     GRADE: 'LRS',
  //     LAST_NAME: 'Van Wiele',
  //     LAYOFF_EXEMPT_RSN: 'AS2022SEC',
  //     NATIONAL_ID: 'BVAN212',
  //     POSITION_DESCR: 'Lecturer',
  //     STEP: 7,
  //     STEP_ENTRY_DT: '2/03/2022',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 1000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Engineering',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '0',
  //     FIRST_NAME: 'Iain',
  //     GRADE: 'PRS',
  //     LAST_NAME: 'Anderson',
  //     LAYOFF_EXEMPT_RSN: 'AS2022CEC',
  //     NATIONAL_ID: 'IAND002',
  //     POSITION_DESCR: 'Professor',
  //     STEP: 0,
  //     STEP_ENTRY_DT: '',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Bioengineering Institute',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '2',
  //     FIRST_NAME: 'Iain',
  //     GRADE: 'PRS',
  //     LAST_NAME: 'Anderson',
  //     LAYOFF_EXEMPT_RSN: 'AS2022CEC',
  //     NATIONAL_ID: 'IAND002',
  //     POSITION_DESCR: 'Professor',
  //     STEP: 0,
  //     STEP_ENTRY_DT: '',
  //     TERMINATION_DT: '',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Permanent',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Medical and Health Sciences',
  //     COMP_RATE_DESCR: 'Medical Loading',
  //     EMPL_RCD: '1',
  //     FIRST_NAME: 'Ian',
  //     GRADE: 'APA',
  //     LAST_NAME: 'Campbell',
  //     LAYOFF_EXEMPT_RSN: 'MAC2022SEC',
  //     NATIONAL_ID: 'ICAM013',
  //     POSITION_DESCR: 'Adjunct Associate Professor',
  //     STEP: 0,
  //     STEP_ENTRY_DT: '',
  //     TERMINATION_DT: '20/10/2024',
  //     UOA_COMPRATE: 20000,
  //     UOA_REG_TEMP_DESCR: 'Fixed Term',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Medical and Health Sciences',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '1',
  //     FIRST_NAME: 'Ian',
  //     GRADE: 'APA',
  //     LAST_NAME: 'Campbell',
  //     LAYOFF_EXEMPT_RSN: 'MAC2022SEC',
  //     NATIONAL_ID: 'ICAM013',
  //     POSITION_DESCR: 'Adjunct Associate Professor',
  //     STEP: 0,
  //     STEP_ENTRY_DT: '',
  //     TERMINATION_DT: '20/10/2024',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Fixed Term',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Medical and Health Sciences',
  //     COMP_RATE_DESCR: 'Medical Loading',
  //     EMPL_RCD: '1',
  //     FIRST_NAME: 'Nicholas',
  //     GRADE: 'SLA',
  //     LAST_NAME: 'Crook',
  //     LAYOFF_EXEMPT_RSN: 'MAC2022SEC',
  //     NATIONAL_ID: 'NCRO016',
  //     POSITION_DESCR: 'Adjunct Senior Lecturer',
  //     STEP: 8,
  //     STEP_ENTRY_DT: '1/02/2022',
  //     TERMINATION_DT: '12/12/2023',
  //     UOA_COMPRATE: 20000,
  //     UOA_REG_TEMP_DESCR: 'Fixed Term',
  //   },
  //   {
  //     BUSINESS_UNIT_DESC: 'Medical and Health Sciences',
  //     COMP_RATE_DESCR: 'Base Salary',
  //     EMPL_RCD: '1',
  //     FIRST_NAME: 'Nicholas',
  //     GRADE: 'SLA',
  //     LAST_NAME: 'Crook',
  //     LAYOFF_EXEMPT_RSN: 'MAC2022SEC',
  //     NATIONAL_ID: 'NCRO016',
  //     POSITION_DESCR: 'Adjunct Senior Lecturer',
  //     STEP: 8,
  //     STEP_ENTRY_DT: '1/02/2022',
  //     TERMINATION_DT: '12/12/2023',
  //     UOA_COMPRATE: 50000,
  //     UOA_REG_TEMP_DESCR: 'Fixed Term',
  //   },
  // ];
}
